
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/context/NextUIProvider";
import AuthProvider from "@/context/AuthProvider";
import React from "react";
import ThemeProvider from "@/context/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
      <AuthProvider>
          <ThemeProvider >
              <Provider>

                  {children}

              </Provider>
          </ThemeProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
